version: '3'
services:
    nginx:
        build:
            context: ./.docker/nginx
        image: nginx
        container_name: nginx
        volumes:
            - ../gas-api-operator-arm:/var/www/gas-api-operator-arm
            - ../gas-api-organizator-arm:/var/www/gas-api-organizator-arm
        ports:
            - 8081:80
            #- 443:443
        restart: always
        depends_on:
            - php-fpm
            - postgres
        networks:
            - app-network

    php-fpm:
        container_name: php-fpm
        volumes:
            - ../gas-api-operator-arm:/var/www/gas-api-operator-arm
            - ../gas-api-organizator-arm:/var/www/gas-api-organizator-arm
        build:
            context: ./.docker/php-fpm
        restart: always
        ports:
            - 9000
        environment:
            XDEBUG_CONFIG: "remote_host=host.docker.internal remote_enable=1"
            PHP_IDE_CONFIG: "serverName=Docker"
        networks:
            - app-network

    postgres:
        container_name: postgres
        image: postgres:11.10
        restart: always
        environment:
            - POSTGRES_MULTIPLE_DATABASES=${DB_DATABASE_ORGANIZATOR},${DB_DATABASE_OPERATOR}
            - POSTGRES_USER=${DB_USERNAME}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        ports:
            - 5432:5432
        volumes:
            - ./.docker/postgres/:/docker-entrypoint-initdb.d/
        build:
            context: ./.docker/postgres
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    mysql-data:
        driver: local